spring.application.name=security.demo
spring.security.user.password=admin
spring.security.user.name=admin

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

#POSTGRE_SQL
spring.datasource.url=jdbc:postgresql://localhost:5431/thousifali
spring.datasource.username=thousifali
#spring.datasource.password=Thousif

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.app.jwtSecret=MySecretasdfjklasdfjkllasdfjkl1234567890789asdfjklasdfjkl
spring.app.jwtExpirationMs=3000000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.springframework.SQL=DEBUG
logging.level.com.example.securitydemo=DEBUG
